namespace: phoenixnap
name: ansible_pnap
version: 0.1.0
readme: README.md
authors:
- Goran Jelenic <goranje@phoenixnap.com>
description: Manage PhoenixNAP Bare Metal Cloud servers
license: GNU General Public License v3.0+
repository: https://github.com/phoenixnap/ansible-pnap