# All the examples assume that you have file config.yaml with your 'clientId' and 'clientSecret'
# in location: ~/.pnap/config.yaml

- name: Delete the SSH Key
  hosts: localhost
  gather_facts: false
  vars_files:
    - ~/.pnap/config.yaml
  collections:
    - phoenixnap.bmc
  tasks:
  - phoenixnap.bmc.ssh_key:
      client_id: "{{clientId}}"
      client_secret: "{{clientSecret}}"
      name: sshkey-name-01
      state: absent