# All the examples assume that you have file config.yaml with your 'clientId' and 'clientSecret'
# in location: ~/.pnap/config.yaml

- name: Show all networks
  hosts: localhost
  gather_facts: false
  vars_files:
    - ~/.pnap/config.yaml
  collections:
    - phoenixnap.bmc
  tasks:
  - phoenixnap.bmc.network_info:
      client_id: "{{clientId}}"
      client_secret: "{{clientSecret}}"
      # filter by name
      #names: [My Default Backend Network, Initial CHI Private Network]
    register: output
  - name: Print the gathered infos
    debug:
      var: output.networks