# All the examples assume that you have file config.yaml with your 'clientId' and 'clientSecret'
# in location: ~/.pnap/config.yaml

- name: Create new tag for account
  hosts: localhost
  gather_facts: false
  vars_files:
    - ~/.pnap/config.yaml
  collections:
    - phoenixnap.bmc
  tasks:
  - phoenixnap.bmc.tag:
      name: Environment
      description: This tag is used for all resources that need to be assigned to an environment.
      is_billing_tag: false
      state: present
    register: output
  - name: Print the tag information
    debug:
      var: output.tags